-- MySQL Script generated by MySQL Workbench
-- 03/26/16 15:40:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ridesharing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ridesharing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ridesharing` DEFAULT CHARACTER SET utf8 ;
USE `ridesharing` ;

-- -----------------------------------------------------
-- Table `ridesharing`.`rides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rides_bjp36` (
  `UUID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `map_point_x` INT UNSIGNED NOT NULL,
  `map_point_y` INT UNSIGNED NOT NULL,
  `date_and_time` MEDIUMTEXT NOT NULL,
  `region` INT UNSIGNED NOT NULL,
  `seats_remaining` INT NOT NULL,
  `is_to_uni` TINYINT(1) NOT NULL,
  `repeating_days` INT NULL,
  `owner_id` INT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
